# -*- mode: ruby -*-
# vi: set ft=ruby :

$verify_nginx = <<SCRIPT
echo inline script: verify nginx listen port 80...
sudo netstat -4nlp | grep -E ':80.*nginx' > /dev/null && \
  echo "inline script: ok" || \
  (err=$?; echo "inline script: failed, quit"; exit $err)
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../provision/", "/vagrant/provision", create: false

  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  config.vm.define "nginx" do |machine|
    machine.vm.hostname = "nginx"
    machine.vm.network "private_network", ip: "192.168.11.2"
    machine.vm.network "forwarded_port", guest: 80, host: 8080

    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook = "provision/single_deploy.yml"
    end
    machine.vm.provision :shell, inline: $verify_nginx
  end
end
