# -*- mode: ruby -*-
# vi: set ft=ruby :

cluster = {
  "aspnet1" => { :ip => "192.168.11.3", :cpus => 1, :mem => 512 },
  "aspnet2" => { :ip => "192.168.11.4", :cpus => 1, :mem => 512 },
  "nginx" => { :ip => "192.168.11.2", :cpus => 1, :mem => 1024 }
}

Vagrant.configure("2") do |config|

  config.vm.synced_folder "../provision/", "/vagrant/provision", create: false
  config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  cluster.each_with_index do |(hostname, info), index|

    config.vm.define hostname do |machine|
      machine.vm.hostname = hostname
      machine.vm.network "private_network", ip: "#{info[:ip]}"

      machine.vm.provision :ansible_local do |ansible|
        ansible.playbook = "provision/three_deploy.yml"
        ansible.skip_tags = "null"
      end
    end
  end # end each_with_index

  config.vm.define "nginx", primary: true do |machine|
    machine.vm.network "forwarded_port", guest: 80, host: 8080

    machine.vm.provision :shell, path: "testlb.sh"
  end

end
